spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/watchbaby?characterEncoding=UTF-8&useSSL=false
    username: root
    password: gyc670894
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.133.130
    # Redis服务器连接端口
    port: 6379

    pool:
    # 连接池最大连接数（使用负值表示没有限制）
      max-active: 20
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
    # 连接池中的最大空闲连接
      max-idle: 8
    # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0
  jpa:
    show-sql: true
server:
  port: 8080

redis:
    key:
       user:
          pre: UID


    expire:
        time: 1280000
